development:
  adapter: postgresql
  encoding: utf8
  database: gaming_development
  pool: 5
  username: viktor
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gaming_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: gaming_production
  pool: 5
  username: viktor
  password: